---@meta

---@class any
---@class nil: any
---@class boolean: any
---@class number: any
---@class integer: number
---@class thread: any
---@class table: any
---@class string: any
---@class userdata: any
---@class lightuserdata: userdata
---@class function:any
